{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Rellm.ContactVerificationAPI exposing
    ( ContactVerificationAPI(..), decodeContactVerificationAPI, defaultContactVerificationAPI, encodeContactVerificationAPI
    , fieldNumbersContactVerificationAPI
    )

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
  - `protoc` 5.29.3
  - the following specification files: `server_configuration.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs ContactVerificationAPI, decodeContactVerificationAPI, defaultContactVerificationAPI, encodeContactVerificationAPI

@docs fieldNumbersContactVerificationAPI

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `ContactVerificationAPI`. This is mostly useful for internals, like documentation generation.
-}
fieldNumbersContactVerificationAPI : ContactVerificationAPI -> Int
fieldNumbersContactVerificationAPI n_ =
    case n_ of
        CONTACTVERIFICATIONAPITWILIO ->
            0

        CONTACTVERIFICATIONAPIBIRD ->
            1

        CONTACTVERIFICATIONAPITELNYX ->
            2

        ContactVerificationAPIUnrecognized_ m_ ->
            m_


{-| Default for ContactVerificationAPI. Should only be used for 'required' decoders as an initial value.
-}
defaultContactVerificationAPI : ContactVerificationAPI
defaultContactVerificationAPI =
    CONTACTVERIFICATIONAPITWILIO


{-| Declares how to encode a `ContactVerificationAPI` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.
-}
encodeContactVerificationAPI : ContactVerificationAPI -> Protobuf.Encode.Encoder
encodeContactVerificationAPI value =
    Protobuf.Encode.int32 <|
        case value of
            CONTACTVERIFICATIONAPITWILIO ->
                0

            CONTACTVERIFICATIONAPIBIRD ->
                1

            CONTACTVERIFICATIONAPITELNYX ->
                2

            ContactVerificationAPIUnrecognized_ i ->
                i


{-| Declares how to decode a `ContactVerificationAPI` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.
-}
decodeContactVerificationAPI : Protobuf.Decode.Decoder ContactVerificationAPI
decodeContactVerificationAPI =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        CONTACTVERIFICATIONAPITWILIO

                    1 ->
                        CONTACTVERIFICATIONAPIBIRD

                    2 ->
                        CONTACTVERIFICATIONAPITELNYX

                    _ ->
                        ContactVerificationAPIUnrecognized_ i
            )


{-| `ContactVerificationAPI` enumeration
-}
type ContactVerificationAPI
    = CONTACTVERIFICATIONAPITWILIO
    | CONTACTVERIFICATIONAPIBIRD
    | CONTACTVERIFICATIONAPITELNYX
    | ContactVerificationAPIUnrecognized_ Int
