{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.ContactProtocol exposing (ContactProtocol(..), decodeContactProtocol, defaultContactProtocol, encodeContactProtocol, fieldNumbersContactProtocol)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `server_configuration.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs ContactProtocol, decodeContactProtocol, defaultContactProtocol, encodeContactProtocol, fieldNumbersContactProtocol

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `ContactProtocol`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersContactProtocol : ContactProtocol -> Int
fieldNumbersContactProtocol n_ =
    case n_ of
        CONTACTPROTOCOLTEL ->
            0

        CONTACTPROTOCOLMAILTO ->
            1

        ContactProtocolUnrecognized_ m_ ->
            m_


{-| Default for ContactProtocol. Should only be used for 'required' decoders as an initial value.

-}
defaultContactProtocol : ContactProtocol
defaultContactProtocol =
    CONTACTPROTOCOLTEL


{-| Declares how to encode a `ContactProtocol` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeContactProtocol : ContactProtocol -> Protobuf.Encode.Encoder
encodeContactProtocol value =
    Protobuf.Encode.int32 <|
        case value of
            CONTACTPROTOCOLTEL ->
                0

            CONTACTPROTOCOLMAILTO ->
                1

            ContactProtocolUnrecognized_ i ->
                i


{-| Declares how to decode a `ContactProtocol` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeContactProtocol : Protobuf.Decode.Decoder ContactProtocol
decodeContactProtocol =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        CONTACTPROTOCOLTEL

                    1 ->
                        CONTACTPROTOCOLMAILTO

                    _ ->
                        ContactProtocolUnrecognized_ i
            )


{-| `ContactProtocol` enumeration

-}
type ContactProtocol
    = CONTACTPROTOCOLTEL
    | CONTACTPROTOCOLMAILTO
    | ContactProtocolUnrecognized_ Int
