{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.ContactConsentState exposing (ContactConsentState(..), decodeContactConsentState, defaultContactConsentState, encodeContactConsentState, fieldNumbersContactConsentState)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `users.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs ContactConsentState, decodeContactConsentState, defaultContactConsentState, encodeContactConsentState

@docs fieldNumbersContactConsentState

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `ContactConsentState`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersContactConsentState : ContactConsentState -> Int
fieldNumbersContactConsentState n_ =
    case n_ of
        CONTACTCONSENTREVOKED ->
            0

        CONTACTCONSENTGRANTED ->
            1

        ContactConsentStateUnrecognized_ m_ ->
            m_


{-| Default for ContactConsentState. Should only be used for 'required' decoders as an initial value.

-}
defaultContactConsentState : ContactConsentState
defaultContactConsentState =
    CONTACTCONSENTREVOKED


{-| Declares how to encode a `ContactConsentState` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeContactConsentState : ContactConsentState -> Protobuf.Encode.Encoder
encodeContactConsentState value =
    Protobuf.Encode.int32 <|
        case value of
            CONTACTCONSENTREVOKED ->
                0

            CONTACTCONSENTGRANTED ->
                1

            ContactConsentStateUnrecognized_ i ->
                i


{-| Declares how to decode a `ContactConsentState` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeContactConsentState : Protobuf.Decode.Decoder ContactConsentState
decodeContactConsentState =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        CONTACTCONSENTREVOKED

                    1 ->
                        CONTACTCONSENTGRANTED

                    _ ->
                        ContactConsentStateUnrecognized_ i
            )


{-| `ContactConsentState` enumeration

-}
type ContactConsentState
    = CONTACTCONSENTREVOKED
    | CONTACTCONSENTGRANTED
    | ContactConsentStateUnrecognized_ Int
