{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.FulfillmentStatus exposing (FulfillmentStatus(..), decodeFulfillmentStatus, defaultFulfillmentStatus, encodeFulfillmentStatus, fieldNumbersFulfillmentStatus)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `market.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs FulfillmentStatus, decodeFulfillmentStatus, defaultFulfillmentStatus, encodeFulfillmentStatus, fieldNumbersFulfillmentStatus

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `FulfillmentStatus`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersFulfillmentStatus : FulfillmentStatus -> Int
fieldNumbersFulfillmentStatus n_ =
    case n_ of
        FULFILLMENTSTATUSAWAITINGHOSTADMIN ->
            0

        FULFILLMENTSTATUSFULFILLED ->
            1

        FULFILLMENTSTATUSINPROGRESS ->
            2

        FulfillmentStatusUnrecognized_ m_ ->
            m_


{-| Default for FulfillmentStatus. Should only be used for 'required' decoders as an initial value.

-}
defaultFulfillmentStatus : FulfillmentStatus
defaultFulfillmentStatus =
    FULFILLMENTSTATUSAWAITINGHOSTADMIN


{-| Declares how to encode a `FulfillmentStatus` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeFulfillmentStatus : FulfillmentStatus -> Protobuf.Encode.Encoder
encodeFulfillmentStatus value =
    Protobuf.Encode.int32 <|
        case value of
            FULFILLMENTSTATUSAWAITINGHOSTADMIN ->
                0

            FULFILLMENTSTATUSFULFILLED ->
                1

            FULFILLMENTSTATUSINPROGRESS ->
                2

            FulfillmentStatusUnrecognized_ i ->
                i


{-| Declares how to decode a `FulfillmentStatus` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeFulfillmentStatus : Protobuf.Decode.Decoder FulfillmentStatus
decodeFulfillmentStatus =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        FULFILLMENTSTATUSAWAITINGHOSTADMIN

                    1 ->
                        FULFILLMENTSTATUSFULFILLED

                    2 ->
                        FULFILLMENTSTATUSINPROGRESS

                    _ ->
                        FulfillmentStatusUnrecognized_ i
            )


{-| `FulfillmentStatus` enumeration

-}
type FulfillmentStatus
    = FULFILLMENTSTATUSAWAITINGHOSTADMIN
    | FULFILLMENTSTATUSFULFILLED
    | FULFILLMENTSTATUSINPROGRESS
    | FulfillmentStatusUnrecognized_ Int
