{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.GetMarketSubscriptionsRequestType exposing (GetMarketSubscriptionsRequestType(..), decodeGetMarketSubscriptionsRequestType, defaultGetMarketSubscriptionsRequestType, encodeGetMarketSubscriptionsRequestType, fieldNumbersGetMarketSubscriptionsRequestType)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `market.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs GetMarketSubscriptionsRequestType, decodeGetMarketSubscriptionsRequestType, defaultGetMarketSubscriptionsRequestType

@docs encodeGetMarketSubscriptionsRequestType, fieldNumbersGetMarketSubscriptionsRequestType

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `GetMarketSubscriptionsRequestType`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersGetMarketSubscriptionsRequestType : GetMarketSubscriptionsRequestType -> Int
fieldNumbersGetMarketSubscriptionsRequestType n_ =
    case n_ of
        GETMARKETSUBSCRIPTIONSREQUESTFORPURCHASE ->
            0

        GETMARKETSUBSCRIPTIONSREQUESTFORFULFILLMENTADMIN ->
            1

        GetMarketSubscriptionsRequestTypeUnrecognized_ m_ ->
            m_


{-| Default for GetMarketSubscriptionsRequestType. Should only be used for 'required' decoders as an initial value.

-}
defaultGetMarketSubscriptionsRequestType : GetMarketSubscriptionsRequestType
defaultGetMarketSubscriptionsRequestType =
    GETMARKETSUBSCRIPTIONSREQUESTFORPURCHASE


{-| Declares how to encode a `GetMarketSubscriptionsRequestType` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeGetMarketSubscriptionsRequestType : GetMarketSubscriptionsRequestType -> Protobuf.Encode.Encoder
encodeGetMarketSubscriptionsRequestType value =
    Protobuf.Encode.int32 <|
        case value of
            GETMARKETSUBSCRIPTIONSREQUESTFORPURCHASE ->
                0

            GETMARKETSUBSCRIPTIONSREQUESTFORFULFILLMENTADMIN ->
                1

            GetMarketSubscriptionsRequestTypeUnrecognized_ i ->
                i


{-| Declares how to decode a `GetMarketSubscriptionsRequestType` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeGetMarketSubscriptionsRequestType : Protobuf.Decode.Decoder GetMarketSubscriptionsRequestType
decodeGetMarketSubscriptionsRequestType =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        GETMARKETSUBSCRIPTIONSREQUESTFORPURCHASE

                    1 ->
                        GETMARKETSUBSCRIPTIONSREQUESTFORFULFILLMENTADMIN

                    _ ->
                        GetMarketSubscriptionsRequestTypeUnrecognized_ i
            )


{-| `GetMarketSubscriptionsRequestType` enumeration

-}
type GetMarketSubscriptionsRequestType
    = GETMARKETSUBSCRIPTIONSREQUESTFORPURCHASE
    | GETMARKETSUBSCRIPTIONSREQUESTFORFULFILLMENTADMIN
    | GetMarketSubscriptionsRequestTypeUnrecognized_ Int
