{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.MarketPurchase exposing (Details)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: ``

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Details

-}

import Proto.Rellm.Internals_


{-| ## Options

### MediaStoragePurchaseDetails

### AiGrantPurchaseDetails

### RellmHostingPurchaseDetails

-}
type alias Details =
    Proto.Rellm.Internals_.Proto__Rellm__MarketPurchase__Details__Details
