{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.MarketPurchase exposing (Details)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: ``

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Details

-}

import Proto.Rellm.Internals_


{-|  Type-specific details for this purchase, matching `type` above -- copied from the
 `MarketProduct.details` (or the buyer-supplied `RellmHostingPurchaseDetails`, for
 `PURCHASE_TYPE_RELLM_HOSTING`) at the moment this purchase was fulfilled, frozen from then on
 even if the originating product later changes. See `logic::market_fulfillment::fulfill_purchase`
 for what each variant actually does to the buyer's account.


## Options

### MediaStoragePurchaseDetails

### AiGrantPurchaseDetails

### RellmHostingPurchaseDetails

### PermissionsAccessPurchaseDetails

-}
type alias Details =
    Proto.Rellm.Internals_.Proto__Rellm__MarketPurchase__Details__Details
