{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.MediaConversion exposing (MediaConversion(..), decodeMediaConversion, defaultMediaConversion, encodeMediaConversion, fieldNumbersMediaConversion)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `media.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs MediaConversion, decodeMediaConversion, defaultMediaConversion, encodeMediaConversion, fieldNumbersMediaConversion

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `MediaConversion`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersMediaConversion : MediaConversion -> Int
fieldNumbersMediaConversion n_ =
    case n_ of
        MEDIACONVERSIONORIGINAL ->
            0

        MEDIACONVERSIONSMALL ->
            1

        MEDIACONVERSIONMEDIUM ->
            2

        MEDIACONVERSIONLARGE ->
            3

        MediaConversionUnrecognized_ m_ ->
            m_


{-| Default for MediaConversion. Should only be used for 'required' decoders as an initial value.

-}
defaultMediaConversion : MediaConversion
defaultMediaConversion =
    MEDIACONVERSIONORIGINAL


{-| Declares how to encode a `MediaConversion` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeMediaConversion : MediaConversion -> Protobuf.Encode.Encoder
encodeMediaConversion value =
    Protobuf.Encode.int32 <|
        case value of
            MEDIACONVERSIONORIGINAL ->
                0

            MEDIACONVERSIONSMALL ->
                1

            MEDIACONVERSIONMEDIUM ->
                2

            MEDIACONVERSIONLARGE ->
                3

            MediaConversionUnrecognized_ i ->
                i


{-| Declares how to decode a `MediaConversion` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeMediaConversion : Protobuf.Decode.Decoder MediaConversion
decodeMediaConversion =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        MEDIACONVERSIONORIGINAL

                    1 ->
                        MEDIACONVERSIONSMALL

                    2 ->
                        MEDIACONVERSIONMEDIUM

                    3 ->
                        MEDIACONVERSIONLARGE

                    _ ->
                        MediaConversionUnrecognized_ i
            )


{-| `MediaConversion` enumeration

-}
type MediaConversion
    = MEDIACONVERSIONORIGINAL
    | MEDIACONVERSIONSMALL
    | MEDIACONVERSIONMEDIUM
    | MEDIACONVERSIONLARGE
    | MediaConversionUnrecognized_ Int
