{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Rellm.NavigationTabStyle exposing
    ( NavigationTabStyle(..), decodeNavigationTabStyle, defaultNavigationTabStyle, encodeNavigationTabStyle
    , fieldNumbersNavigationTabStyle
    )

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
  - `protoc` 5.29.3
  - the following specification files: `server_configuration.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs NavigationTabStyle, decodeNavigationTabStyle, defaultNavigationTabStyle, encodeNavigationTabStyle

@docs fieldNumbersNavigationTabStyle

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `NavigationTabStyle`. This is mostly useful for internals, like documentation generation.
-}
fieldNumbersNavigationTabStyle : NavigationTabStyle -> Int
fieldNumbersNavigationTabStyle n_ =
    case n_ of
        NAVIGATIONTABICONONLY ->
            0

        NAVIGATIONTABTEXTONLY ->
            1

        NAVIGATIONTABICONANDTEXTBELOW ->
            2

        NAVIGATIONTABICONANDTEXTRIGHT ->
            3

        NavigationTabStyleUnrecognized_ m_ ->
            m_


{-| Default for NavigationTabStyle. Should only be used for 'required' decoders as an initial value.
-}
defaultNavigationTabStyle : NavigationTabStyle
defaultNavigationTabStyle =
    NAVIGATIONTABICONONLY


{-| Declares how to encode a `NavigationTabStyle` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.
-}
encodeNavigationTabStyle : NavigationTabStyle -> Protobuf.Encode.Encoder
encodeNavigationTabStyle value =
    Protobuf.Encode.int32 <|
        case value of
            NAVIGATIONTABICONONLY ->
                0

            NAVIGATIONTABTEXTONLY ->
                1

            NAVIGATIONTABICONANDTEXTBELOW ->
                2

            NAVIGATIONTABICONANDTEXTRIGHT ->
                3

            NavigationTabStyleUnrecognized_ i ->
                i


{-| Declares how to decode a `NavigationTabStyle` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.
-}
decodeNavigationTabStyle : Protobuf.Decode.Decoder NavigationTabStyle
decodeNavigationTabStyle =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        NAVIGATIONTABICONONLY

                    1 ->
                        NAVIGATIONTABTEXTONLY

                    2 ->
                        NAVIGATIONTABICONANDTEXTBELOW

                    3 ->
                        NAVIGATIONTABICONANDTEXTRIGHT

                    _ ->
                        NavigationTabStyleUnrecognized_ i
            )


{-| `NavigationTabStyle` enumeration
-}
type NavigationTabStyle
    = NAVIGATIONTABICONONLY
    | NAVIGATIONTABTEXTONLY
    | NAVIGATIONTABICONANDTEXTBELOW
    | NAVIGATIONTABICONANDTEXTRIGHT
    | NavigationTabStyleUnrecognized_ Int
