{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Rellm.PurchaseType exposing (PurchaseType(..), decodePurchaseType, defaultPurchaseType, encodePurchaseType, fieldNumbersPurchaseType)

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
  - `protoc` 5.29.3
  - the following specification files: `market.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs PurchaseType, decodePurchaseType, defaultPurchaseType, encodePurchaseType, fieldNumbersPurchaseType

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `PurchaseType`. This is mostly useful for internals, like documentation generation.
-}
fieldNumbersPurchaseType : PurchaseType -> Int
fieldNumbersPurchaseType n_ =
    case n_ of
        PURCHASETYPEMEDIASTORAGE ->
            0

        PURCHASETYPEAIGRANTS ->
            1

        PURCHASETYPERELLMHOSTING ->
            2

        PURCHASETYPEPERMISSIONSACCESS ->
            3

        PurchaseTypeUnrecognized_ m_ ->
            m_


{-| Default for PurchaseType. Should only be used for 'required' decoders as an initial value.
-}
defaultPurchaseType : PurchaseType
defaultPurchaseType =
    PURCHASETYPEMEDIASTORAGE


{-| Declares how to encode a `PurchaseType` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.
-}
encodePurchaseType : PurchaseType -> Protobuf.Encode.Encoder
encodePurchaseType value =
    Protobuf.Encode.int32 <|
        case value of
            PURCHASETYPEMEDIASTORAGE ->
                0

            PURCHASETYPEAIGRANTS ->
                1

            PURCHASETYPERELLMHOSTING ->
                2

            PURCHASETYPEPERMISSIONSACCESS ->
                3

            PurchaseTypeUnrecognized_ i ->
                i


{-| Declares how to decode a `PurchaseType` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.
-}
decodePurchaseType : Protobuf.Decode.Decoder PurchaseType
decodePurchaseType =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        PURCHASETYPEMEDIASTORAGE

                    1 ->
                        PURCHASETYPEAIGRANTS

                    2 ->
                        PURCHASETYPERELLMHOSTING

                    3 ->
                        PURCHASETYPEPERMISSIONSACCESS

                    _ ->
                        PurchaseTypeUnrecognized_ i
            )


{-| `PurchaseType` enumeration
-}
type PurchaseType
    = PURCHASETYPEMEDIASTORAGE
    | PURCHASETYPEAIGRANTS
    | PURCHASETYPERELLMHOSTING
    | PURCHASETYPEPERMISSIONSACCESS
    | PurchaseTypeUnrecognized_ Int
