{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Rellm.PurchasePeriod exposing (PurchasePeriod(..), decodePurchasePeriod, defaultPurchasePeriod, encodePurchasePeriod, fieldNumbersPurchasePeriod)

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
  - `protoc` 5.29.3
  - the following specification files: `market.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs PurchasePeriod, decodePurchasePeriod, defaultPurchasePeriod, encodePurchasePeriod, fieldNumbersPurchasePeriod

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `PurchasePeriod`. This is mostly useful for internals, like documentation generation.
-}
fieldNumbersPurchasePeriod : PurchasePeriod -> Int
fieldNumbersPurchasePeriod n_ =
    case n_ of
        PURCHASEPERIODINDEFINITE ->
            0

        PURCHASEPERIODANNUAL ->
            1

        PURCHASEPERIODMONTHLY ->
            2

        PurchasePeriodUnrecognized_ m_ ->
            m_


{-| Default for PurchasePeriod. Should only be used for 'required' decoders as an initial value.
-}
defaultPurchasePeriod : PurchasePeriod
defaultPurchasePeriod =
    PURCHASEPERIODINDEFINITE


{-| Declares how to encode a `PurchasePeriod` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.
-}
encodePurchasePeriod : PurchasePeriod -> Protobuf.Encode.Encoder
encodePurchasePeriod value =
    Protobuf.Encode.int32 <|
        case value of
            PURCHASEPERIODINDEFINITE ->
                0

            PURCHASEPERIODANNUAL ->
                1

            PURCHASEPERIODMONTHLY ->
                2

            PurchasePeriodUnrecognized_ i ->
                i


{-| Declares how to decode a `PurchasePeriod` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.
-}
decodePurchasePeriod : Protobuf.Decode.Decoder PurchasePeriod
decodePurchasePeriod =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        PURCHASEPERIODINDEFINITE

                    1 ->
                        PURCHASEPERIODANNUAL

                    2 ->
                        PURCHASEPERIODMONTHLY

                    _ ->
                        PurchasePeriodUnrecognized_ i
            )


{-| `PurchasePeriod` enumeration
-}
type PurchasePeriod
    = PURCHASEPERIODINDEFINITE
    | PURCHASEPERIODANNUAL
    | PURCHASEPERIODMONTHLY
    | PurchasePeriodUnrecognized_ Int
