{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.RsvpStatus exposing (RsvpStatus(..), decodeRsvpStatus, defaultRsvpStatus, encodeRsvpStatus, fieldNumbersRsvpStatus)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `events.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs RsvpStatus, decodeRsvpStatus, defaultRsvpStatus, encodeRsvpStatus, fieldNumbersRsvpStatus

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `RsvpStatus`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersRsvpStatus : RsvpStatus -> Int
fieldNumbersRsvpStatus n_ =
    case n_ of
        INTERESTED ->
            0

        REQUESTED ->
            1

        GOING ->
            2

        NOTGOING ->
            3

        RsvpStatusUnrecognized_ m_ ->
            m_


{-| Default for RsvpStatus. Should only be used for 'required' decoders as an initial value.

-}
defaultRsvpStatus : RsvpStatus
defaultRsvpStatus =
    INTERESTED


{-| Declares how to encode a `RsvpStatus` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeRsvpStatus : RsvpStatus -> Protobuf.Encode.Encoder
encodeRsvpStatus value =
    Protobuf.Encode.int32 <|
        case value of
            INTERESTED ->
                0

            REQUESTED ->
                1

            GOING ->
                2

            NOTGOING ->
                3

            RsvpStatusUnrecognized_ i ->
                i


{-| Declares how to decode a `RsvpStatus` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeRsvpStatus : Protobuf.Decode.Decoder RsvpStatus
decodeRsvpStatus =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        INTERESTED

                    1 ->
                        REQUESTED

                    2 ->
                        GOING

                    3 ->
                        NOTGOING

                    _ ->
                        RsvpStatusUnrecognized_ i
            )


{-| `RsvpStatus` enumeration

-}
type RsvpStatus
    = INTERESTED
    | REQUESTED
    | GOING
    | NOTGOING
    | RsvpStatusUnrecognized_ Int
