{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Rellm.MarketSubscription.Details exposing (Details(..))

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
  - `protoc` 5.29.3
  - the following specification files: `market.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Details

-}


{-| Type-specific details for this subscription, matching `type` above -- copied from the
originating `MarketProduct.details` at creation time (or, for `PURCHASE_TYPE_RELLM_HOSTING`,
built from the buyer's own checkout-time input -- see `RellmHostingPurchaseDetails`'s own doc
for the same caveat that applies here), frozen from then on even if the product later changes.
Re-applied on every renewal via `logic::market_fulfillment::fulfill_purchase`, and read back by
`logic::market_fulfillment::terminate_entitlement` to know exactly what to claw back on
cancellation.


## Options


### MediaStorageSubscriptionDetails


### AiGrantSubscriptionDetails


### RellmHostingSubscriptionDetails


### PermissionsAccessSubscriptionDetails

-}
type Details a0 a1 a2 a3
    = MediaStorageSubscriptionDetails a0
    | AiGrantSubscriptionDetails a1
    | RellmHostingSubscriptionDetails a2
    | PermissionsAccessSubscriptionDetails a3
