#![allow(non_snake_case)]
// This module - a compiled rellm.proto - is generated by prost-build.
mod rellm;
pub use self::rellm::*;

/// Deserializes a plain `string` field that used to be `optional string` -- some already-stored
/// `server_configurations` rows (from before `TwilioConfig`/`TelnyxConfig`/`BirdConfig`'s
/// `*_webhook_signing_key` fields switched from `optional string` to plain `string`, see their own
/// doc in `server_configuration.proto`) have it stored as literal JSON `null` (serde's encoding of
/// `Option::None`). Treats that `null` the same as a missing key: both fall back to
/// `String::new()`. Paired with `#[serde(default)]` on the same field (see `build.rs`'s own
/// `field_attribute` for these fields) -- `default` alone only covers a *missing* key, not one
/// present with an explicit `null` value, which is why this also needs `deserialize_with`.
pub fn deserialize_string_or_null<'de, D>(deserializer: D) -> Result<String, D::Error>
where
    D: serde::Deserializer<'de>,
{
    use serde::Deserialize;
    Ok(Option::<String>::deserialize(deserializer)?.unwrap_or_default())
}
