{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Rellm.MarketPurchase.Details exposing (Details(..))

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
  - `protoc` 5.29.3
  - the following specification files: `market.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Details

-}


{-| Type-specific details for this purchase, matching `type` above -- copied from the
`MarketProduct.details` (or the buyer-supplied `RellmHostingPurchaseDetails`, for
`PURCHASE_TYPE_RELLM_HOSTING`) at the moment this purchase was fulfilled, frozen from then on
even if the originating product later changes. See `logic::market_fulfillment::fulfill_purchase`
for what each variant actually does to the buyer's account.


## Options


### MediaStoragePurchaseDetails


### AiGrantPurchaseDetails


### RellmHostingPurchaseDetails


### PermissionsAccessPurchaseDetails

-}
type Details a0 a1 a2 a3
    = MediaStoragePurchaseDetails a0
    | AiGrantPurchaseDetails a1
    | RellmHostingPurchaseDetails a2
    | PermissionsAccessPurchaseDetails a3
