{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.MarketPurchase.Details exposing (Details(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `market.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Details

-}


{-| ## Options

### MediaStoragePurchaseDetails

### AiGrantPurchaseDetails

### RellmHostingPurchaseDetails

-}
type Details a0 a1 a2
    = MediaStoragePurchaseDetails a0
    | AiGrantPurchaseDetails a1
    | RellmHostingPurchaseDetails a2
