{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.MarketProduct.Details exposing (Details(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `market.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Details

-}


{-| ## Options

### MediaStorageSubscriptionDetails

### AiGrantSubscriptionDetails

### RellmHostingSubscriptionDetails

### PermissionsAccessSubscriptionDetails

-}
type Details a0 a1 a2 a3
    = MediaStorageSubscriptionDetails a0
    | AiGrantSubscriptionDetails a1
    | RellmHostingSubscriptionDetails a2
    | PermissionsAccessSubscriptionDetails a3
