{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Rellm.MarketProduct.Details exposing (Details(..))

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
  - `protoc` 5.29.3
  - the following specification files: `market.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Details

-}


{-| Type-specific configuration for this product, matching `type` above -- e.g. how much media
storage a `PURCHASE_TYPE_MEDIA_STORAGE` product grants, or which AI provider/models a
`PURCHASE_TYPE_AI_GRANTS` product grants tokens for. Copied onto every `MarketPurchase`/
`MarketSubscription` created from this product at the time of purchase (as that purchase's own
`details`), so a later edit to this product's own `details` never retroactively changes what an
existing buyer already bought.


## Options


### MediaStorageSubscriptionDetails


### AiGrantSubscriptionDetails


### RellmHostingSubscriptionDetails


### PermissionsAccessSubscriptionDetails

-}
type Details a0 a1 a2 a3
    = MediaStorageSubscriptionDetails a0
    | AiGrantSubscriptionDetails a1
    | RellmHostingSubscriptionDetails a2
    | PermissionsAccessSubscriptionDetails a3
